import React from 'react';
import { Download, Image, FileText } from 'lucide-react';
import { useStore } from '../store/useStore';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { toast } from 'sonner';

export function ExportButtons() {
  const { nodes } = useStore();
  const [isExporting, setIsExporting] = React.useState(false);
  
  const exportCanvasAsPNG = async () => {
    setIsExporting(true);
    try {
      const canvasElement = document.querySelector('.react-flow') as HTMLElement;
      if (!canvasElement) {
        toast.error('Canvas not found');
        return;
      }
      
      const canvas = await html2canvas(canvasElement, {
        backgroundColor: '#e3e3e3', // var(--sc-canvas-bg)
        scale: 2
      });
      
      const link = document.createElement('a');
      link.download = 'sparkmap-canvas.png';
      link.href = canvas.toDataURL();
      link.click();
      
      toast.success('Canvas exported as PNG');
    } catch (error) {
      console.error('Export error:', error);
      toast.error('Failed to export canvas');
    } finally {
      setIsExporting(false);
    }
  };
  
  const exportFlashcardsAsPDF = () => {
    setIsExporting(true);
    try {
      const flashcardNodes = nodes.filter(n => n.data.flashcard && !n.data.isGroup);
      
      if (flashcardNodes.length === 0) {
        toast.error('No flashcards to export');
        return;
      }
      
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      
      flashcardNodes.forEach((node, index) => {
        if (index > 0) {
          doc.addPage();
        }
        
        const flashcard = node.data.flashcard!;
        
        // Title
        doc.setFontSize(16);
        doc.setTextColor(124, 100, 182); // sc-purple
        doc.text(`Flashcard ${index + 1}`, margin, margin);
        
        // Question
        doc.setFontSize(12);
        doc.setTextColor(36, 51, 81); // sc-blue-text
        doc.text('Question:', margin, margin + 15);
        
        doc.setFontSize(10);
        doc.setTextColor(119, 119, 119); // sc-text-muted
        const questionLines = doc.splitTextToSize(flashcard.question, pageWidth - 2 * margin);
        doc.text(questionLines, margin, margin + 25);
        
        // Answer
        const answerY = margin + 25 + questionLines.length * 7 + 15;
        doc.setFontSize(12);
        doc.setTextColor(36, 51, 81);
        doc.text('Answer:', margin, answerY);
        
        doc.setFontSize(10);
        doc.setTextColor(119, 119, 119);
        const answerLines = doc.splitTextToSize(flashcard.answer, pageWidth - 2 * margin);
        doc.text(answerLines, margin, answerY + 10);
        
        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by Sparkmap', margin, pageHeight - 10);
      });
      
      doc.save('sparkmap-flashcards.pdf');
      toast.success(`Exported ${flashcardNodes.length} flashcards`);
    } catch (error) {
      console.error('Export error:', error);
      toast.error('Failed to export flashcards');
    } finally {
      setIsExporting(false);
    }
  };
  
  return (
    <div className="flex gap-2">
      <button
        onClick={exportCanvasAsPNG}
        disabled={isExporting || nodes.length === 0}
        className="btn-action"
      >
        <Image className="w-4 h-4" />
        <span className="hidden sm:inline">Export PNG</span>
      </button>
      
      <button
        onClick={exportFlashcardsAsPDF}
        disabled={isExporting || nodes.filter(n => n.data.flashcard).length === 0}
        className="btn-action"
      >
        <FileText className="w-4 h-4" />
        <span className="hidden sm:inline">Export PDF</span>
      </button>
    </div>
  );
}