import React from 'react';
import { Download, Image, FileText, ChevronDown } from 'lucide-react';
import { useStore } from '../store/useStore';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { toast } from 'sonner';

export function ExportButtons() {
  const { nodes } = useStore();
  const [isExporting, setIsExporting] = React.useState(false);
  const [showMenu, setShowMenu] = React.useState(false);
  const menuRef = React.useRef<HTMLDivElement>(null);
  
  // Close menu when clicking outside
  React.useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(event.target as Node)) {
        setShowMenu(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const exportCanvasAsPNG = async () => {
    setShowMenu(false);
    setIsExporting(true);
    try {
      const canvasElement = document.querySelector('.react-flow') as HTMLElement;
      if (!canvasElement) {
        toast.error('Canvas not found');
        return;
      }
      
      const canvas = await html2canvas(canvasElement, {
        backgroundColor: '#e3e3e3',
        scale: 2,
        useCORS: true,
        allowTaint: true,
        foreignObjectRendering: true,
        logging: false
      });
      
      const link = document.createElement('a');
      link.download = 'sparkmap-canvas.png';
      link.href = canvas.toDataURL('image/png', 1.0);
      link.click();
      
      toast.success('Canvas exported as PNG');
    } catch (error) {
      console.error('Export error:', error);
      toast.error('Failed to export canvas');
    } finally {
      setIsExporting(false);
    }
  };
  
  const exportFlashcardsAsPDF = () => {
    setShowMenu(false);
    setIsExporting(true);
    try {
      const flashcardNodes = nodes.filter(n => n.data.flashcard && !n.data.isGroup);
      
      if (flashcardNodes.length === 0) {
        toast.error('No flashcards to export');
        return;
      }
      
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      
      flashcardNodes.forEach((node, index) => {
        if (index > 0) doc.addPage();
        const flashcard = node.data.flashcard!;
        doc.setFontSize(16);
        doc.setTextColor(124, 100, 182);
        doc.text(`Flashcard ${index + 1}`, margin, margin);
        doc.setFontSize(12);
        doc.setTextColor(36, 51, 81);
        doc.text('Question:', margin, margin + 15);
        doc.setFontSize(10);
        doc.setTextColor(119, 119, 119);
        const questionLines = doc.splitTextToSize(flashcard.question, pageWidth - 2 * margin);
        doc.text(questionLines, margin, margin + 25);
        const answerY = margin + 25 + questionLines.length * 7 + 15;
        doc.setFontSize(12);
        doc.setTextColor(36, 51, 81);
        doc.text('Answer:', margin, answerY);
        doc.setFontSize(10);
        doc.setTextColor(119, 119, 119);
        const answerLines = doc.splitTextToSize(flashcard.answer, pageWidth - 2 * margin);
        doc.text(answerLines, margin, answerY + 10);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by Sparkmap', margin, pageHeight - 10);
      });
      
      doc.save('sparkmap-flashcards.pdf');
      toast.success(`Exported ${flashcardNodes.length} flashcards`);
    } catch (error) {
      console.error('Export error:', error);
      toast.error('Failed to export flashcards');
    } finally {
      setIsExporting(false);
    }
  };
  
  return (
    <div className="relative" ref={menuRef}>
      <button
        onClick={() => setShowMenu(!showMenu)}
        disabled={isExporting || nodes.length === 0}
        className="btn-action flex items-center gap-2 px-4 whitespace-nowrap"
        aria-haspopup="true"
        aria-expanded={showMenu}
      >
        <Download className={`w-4 h-4 ${isExporting ? 'animate-pulse' : ''}`} />
        <span className="font-medium text-[13px]">Export Workspace</span>
        <ChevronDown className={`w-3.5 h-3.5 transition-transform duration-200 ${showMenu ? 'rotate-180' : ''}`} />
      </button>

      {showMenu && (
        <div className="absolute top-[calc(100%+12px)] right-0 w-[260px] bg-[var(--sc-surface-card)] rounded-[16px] border border-[var(--sc-border)] shadow-2xl overflow-hidden animate-in fade-in slide-in-from-top-2 duration-200 z-[1001]">
          <div className="px-4 py-3 border-b border-[var(--sc-border-light)] bg-[var(--sc-surface-alt)]">
            <h4 className="text-[12px] font-bold text-[var(--sc-text-primary)] m-0">Export Options</h4>
            <p className="text-[10px] text-[var(--sc-text-muted)] m-0 mt-0.5">Save your workspace locally</p>
          </div>
          <div className="p-2 flex flex-col gap-1">
            <button
              onClick={exportCanvasAsPNG}
              className="group flex items-start gap-3 w-full p-3 text-left hover:bg-[var(--sc-surface-hover)] hover:shadow-sm rounded-[12px] border border-transparent hover:border-[var(--sc-border-light)] transition-all"
            >
              <div className="w-8 h-8 mt-0.5 shrink-0 rounded-[8px] bg-blue-50 text-blue-600 dark:bg-blue-500/10 dark:text-blue-400 flex items-center justify-center group-hover:scale-105 transition-transform">
                <Image className="w-4 h-4" />
              </div>
              <div className="flex flex-col">
                <span className="text-[13px] font-semibold text-[var(--sc-text-primary)] group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">Download PNG</span>
                <span className="text-[11px] leading-snug text-[var(--sc-text-secondary)] mt-0.5">High-resolution snapshot of your entire knowledge graph</span>
              </div>
            </button>
            <button
              onClick={exportFlashcardsAsPDF}
              className="group flex items-start gap-3 w-full p-3 text-left hover:bg-[var(--sc-surface-hover)] hover:shadow-sm rounded-[12px] border border-transparent hover:border-[var(--sc-border-light)] transition-all"
            >
              <div className="w-8 h-8 mt-0.5 shrink-0 rounded-[8px] bg-purple-50 text-purple-600 dark:bg-purple-500/10 dark:text-purple-400 flex items-center justify-center group-hover:scale-105 transition-transform">
                <FileText className="w-4 h-4" />
              </div>
              <div className="flex flex-col">
                <span className="text-[13px] font-semibold text-[var(--sc-text-primary)] group-hover:text-purple-600 dark:group-hover:text-purple-400 transition-colors">Flashcards PDF</span>
                <span className="text-[11px] leading-snug text-[var(--sc-text-secondary)] mt-0.5">Printable study cards from your generated concepts</span>
              </div>
            </button>
          </div>
        </div>
      )}
    </div>
  );
}